MarechJ/hll_rcon_tool

rcon/broadcast.py, rcon/extended_commands.py, rcongui/src/components/RconSettings/rconSettings.js, rcongui/src/components/SettingsView/serverMessage.js
Added {{vips}} and {{randomvip}} broadcasting variables.
=> Added variables for broadcasting all vips and a random vip

manage.py, rcon/game_logs.py
=> Click does not return error code on error

Dockerfile-arm64, docker-compose.arm64v8.yml, rcongui/Dockerfile-arm64
Created arm64v8 files to support the Raspberry Pi 4. 
Used python3.8.5 & node14
=> Add arm64v8 support

.env, docker-compose-common-components.yml, docker-compose.yml, rcon/player_history.py, rcon/steam_utils.py
Implemented a config that allows admins to automatically ban players that received a VAC/Game ban within the past N days
=> Feature/Add config to auto-ban based on recent VAC bans

rcongui/src/components/PlayerView/playerList.js
Request secure URL if using secure address.
=> Added window protocol to external playerView resources

rcon/cli.py, rcon/extended_commands.py
Added this extra command so we can mimic the upload_vips feature via command line
=> Added in a remove_all_vips command

rcongui/src/App.js, rcongui/src/components/RconSettings/autoSettings.js, rcongui/src/components/RconSettings/rconSettings.js
=> Implement adaptive theme for auto-settings editor

rcon/models.py
Remove PlayerVIP which was added twice when resolving merge conflicts
=> Remove duplicate PlayerVIP relation

config/default_config.yml, rcon/squad_automod/automod.py, rcon/squad_automod/models.py, tests/test_no_leader_watch.py
Does build successfully and looked as if it is still running as it is supposed to.
If anyone has the server and time capacity to test it properly I would be thankful
=> Clean up and improve automod

rcon/extended_commands.py
GameView of this branch (left side) vs prod (right side), seems to be working fine
=> Fix commander bug in team view

rcon/automods/no_leader.py
Fixes a missing argument for the no leader automod (from integrating a new seeding automod rule)
=> Add missing positional argument

rcon/commands.py, rcon/extended_commands.py, rcon/utils.py, rcongui/src/components/MapManager/settings.js, rcongui/src/components/SettingsView/hllSettings.js
This is all untested right now, until I've found a server, which's MapRotation.ini is fixed already.
=> Fixes for U14 fuckups

rcongui/src/components/GameView/index.js
Switch the axis/allied components on the game view so they match the format seen at the top and returned by the game state commands.
=> Swap axis/allied game view components to match objective score format

rcongui/src/components/Scoreboard/Scores.js
This adds tables for the combat effectiveness, attack, defense and support scores that are shown on the in-game scoreboard to the public stats page.
=> rcongui: Add RankBoards to show in-game scoreboard points

rcongui/src/components/Scoreboard/GamesScore.js, rcongui/src/components/Scoreboard/LiveScore.js, rcongui/src/components/Scoreboard/Scores.js, rcongui/src/components/useStyles.js
The stats page had a horizontal scrollbar. Reorganizing the grids for a bit solves this.
=> rcongui: Fix stats page horizontal scroll

rcon/steam_utils.py
1. Fixed probable typo errors (wrong object reference : logging. -> logger.)
2. Adds a log error message when Steam API throws a "Too Many Requests" error
=> Bad logger call + better error handling

requirements.txt
These have compatible versions now, I let this record a game just to be sure everything was working correctly.
=> Bump rq/rq-scheduler to latest versions

rcon/user_config/auto_mod_level.py, rcon/user_config/auto_mod_no_leader.py, rcon/user_config/auto_mod_seeding.py, rcon/user_config/auto_mod_solo_tank.py
* Update the constraint for automod punishments to allow for `-1` which causes infinite punishments.
=> Allow -1 (infinite) punishments

rcongui/src/App.js, rcongui/src/components/UserSettings/miscellaneous.js
* Fixes the documentation for the GTX server name change config
=> Add documentation for the server name change config

rconweb/api/utils.py
* Correctly handle requests that contain form data but not a JSON body
I tested this, VIP upload/download works properly again and it doesn't affect other API requests.
=> Fix VIP uploads

rcongui/src/App.js
Bad id, probably from a copy-paste error (?)
=> Fix---UI-Automod-NoSoloTank-Update App.js

rcon/steam_utils.py
* Only log the warning when a steam API key is not set every 5 minutes
* Don't log the warning when bans can't be read when players are connected
These two things would fill up your logs with mostly useless information and it's very annoying especially when you're trying to watch the logs for something else.
=> Reduce steam utility log spam

rcon/cli.py
* Log the reason database enrichment failed if it fails
=> Log the reason db enrichment failed

rcongui/src/components/VipDialog/index.js
Courtesy of AjaxNine from the Discord.
Improves the VIP dialog UI by adding buttons for common VIP increments.
Old:
New:
=> Improve VIP dialog

README.md, dev.env, rcon/cache_utils.py, rconweb/rconweb/settings.py
* Update README to reflect changes in how to set up a development environment
* Update README to remove/improve some out dated information
* Allow `redis` to work properly when running a local development instance
* Update Django settings when running in `DEBUG` mode to allow cookies in Chrome to work properly
=> Development instances

rcon/discord_chat.py, tests/test_discord_handler.py
Allow numbers in admin ping words.
=> Allow numbers in admin pings

rcon/automods/no_leader.py, rcon/user_config/auto_mod_no_leader.py, rcongui/src/components/UserSettings/autoMods.js, tests/test_no_leader_watch.py
Add an option to disable the automod when the number of players is below a configurable number.
=> Feature automod no leader seed limit activation

rcon/user_config/rcon_server_settings.py, rcongui/src/components/UserSettings/miscellaneous.js
I failed to validate the actions for windows store players correctly, I checked them all this time.
=> Validate windows store player actions correctly

rconweb/api/multi_servers.py
* Change server forwarding to use `POST` instead of `GET`
* Fall back to a `GET` request if it returns a `405 Method Not Allowed` error
This broke when we added the `HttpResponseNotAllowed` checks. Tested it and it works just fine now.
=> Fix server forwarding due to HTTP method checking

rcon/automods/level_thresholds.py, rcon/user_config/auto_mod_level.py, rcongui/src/components/UserSettings/autoMods.js
Adds a parameter to allow admins to enable/disable the "level 1 bug" protection.
=> Feature automod level level1 bug protection enable/disable

rcon/win_store_utils.py, rconweb/api/vips.py
Add a check so that VIP upload will accept both steam ids and windows store ids. Manually tested.
=> fix vip upload only accepts steam ids, not windows store ids

rcon/cli.py
The CLI registration needs to be done when the file is imported to be registered with `click`, I broke this when I moved it into the command.
Verified it works correctly now.
=> Fix rcon command line registration

rconweb/api/models.py
Fix a few typos, no actual code changes.
=> Fix typoes in descriptions

README.md
Update the README as it's quite out of date and important information (like installation steps) has changed
=> Readme    wip

rcon/automods/seeding_rules.py
I did not explicitly test this but it should work correctly.
=> Disable enforce_cap_fight for skirmish maps

rcongui/src/components/MapManager/DraggableListItem.js, rcongui/src/components/Scoreboard/utils.js
This is super quick and dirty and gross (but it does work) and we should come back to it after the API returns more useful map information (thanks Abu)
=> Fix map rotation UI for skirmish maps

rcongui/src/components/GameView/index.js
sort the gameview playersname automplete widget
=> Sort players list drop-down in the game view

rcon/vote_map.py
Fixes an unbound variable that was causing votemap reminders to fail.
=> Fix unbound variable issue

rcon/steam_utils.py
* Only actually call the steam API if a steam API key is set (cuts down on **a lot** of unnecessary log errors)
* Add new `SteamInfo` records to the session so they're persisted in the database, I misunderstood how `sqlalchemy` handles these things and new player records were not persisting properly.
I built this and did quite a bit of manual testing making sure everything works properly, I believe there are still issues with `enrich_db_users` but that's a side issue.
=> Only attempt Steam API calls if an API key is set

rcon/scorebot.py
Fixes https://github.com/MarechJ/hll_rcon_tool/issues/550
=> Set elapsed_time_minutes to 0 if the match start time is unavailable

.gitignore
=> Add /logs in .gitignore

rcon/auto_kick.py
FIX - new kick() function player_name parameter wasn't updated in auto_kick.py
=> FIX - new kick() function player_name parameter wasn't updated

.gitignore, rcongui/src/components/Blacklist/BlacklistRecordCreateDialog.js, rcongui/src/components/Blacklist/BlacklistRecordGrid.js, rcongui/src/components/Blacklist/BlacklistRecords.js, rcongui/src/components/GameView/index.js, rcongui/src/components/PlayerView/playerActions.js, rcongui/src/components/PlayerView/playerList.js, rcongui/src/components/PlayerView/playerView.js, rcongui/src/utils/fetchUtils.js
Implemented dialog windows for adding players to Blacklists directly from `GameView` and `LiveView`
- A user is able to blacklist all selected players
- A user is able to blacklist a single player
_This is a subject to change as I did not fully understand the initial idea behind the helper text content. I hope I got it right._
- Updated "blacklist form input helper text" by following conditions
- `blacklist.servers === []` -> _"This blacklist does not affect any servers!"_
-  `blacklist.servers === [s1, s2, ...] & current_server NOT IN blacklist.servers` -> _"This blacklist DOES NOT affect THIS server! Affected servers: [s1, s2, ...]"_
Example: Multiple players selected
=> UI: Blacklist dialog for GameView and PlayerView

rcongui/src/components/Header/nav-data.js
missing chat webhooks link + bad nosolotank url
=> missing chat webhooks link + bad nosolotank url

rcongui/src/components/Blacklist/BlacklistRecordCreateDialog.js, rcongui/src/components/Blacklist/BlacklistRecordGrid.js, rcongui/src/components/GameView/index.js, rcongui/src/components/MapManager/map-rotation/map-rotation-config.jsx, rcongui/src/components/PlayerView/playerView.js, rcongui/src/components/VipDialog/index.js, rcongui/src/components/shared/time-picker-buttons.jsx
- Fix ->  #661 
- Fix -> when a user without edit blacklist record permissions clicked on "Expire this record", it optimistically updated the UI
- New presets -> as there are requests for different time presets I decided to implement the same buttons as for the vip dialog
=> UI: Blacklist app crash fix and other changes

rcongui/src/components/Blacklist/BlacklistListTile.js, rcongui/src/components/Blacklist/BlacklistLists.js, rcongui/src/components/Blacklist/BlacklistRecords.js
=> Blacklist delete confirmation dialog

rcon/user_config/log_stream.py, rcon/user_config/real_vip.py, rcon/user_config/seed_vip.py, rcon/user_config/webhooks.py
Adds the missing optional key parameter that was missing in a few places.
I built/tested it locally and each one works correctly now.
=> Add missing parameters

rconweb/api/services.py
* Resolves #723 
* Catches a new type of error I saw while rapidly toggling the service on/off
We can rename the service still, not sure what name would be better.
=> Make do_service output consistent

rcongui/src/pages/dashboard.jsx, rcongui/src/pages/stats/games/[gameId]/index.jsx
App crashes when game.result = null.
Fixed all occurrences of `result.axis` or `result.allied` in the codebase.
=> fix game results rendering being null

rcongui/src/features/player-action/actions.js, rcongui/src/features/player-action/forms/AddConsoleAdminFormFields.jsx
=> UI: Added console admin action

rcongui/src/components/shared/PopoverMenu.jsx, rcongui/src/components/table/selection/LogActionHighlightMenu.jsx, rcongui/src/components/table/selection/LogActionSelectionMenu.jsx, rcongui/src/components/table/selection/LogPlayerSelectionMenu.jsx, rcongui/src/hooks/useSelectionMenu.js
=> UI: Log table selection search and stop scrolling upwards

rcongui/src/pages/records/audit-logs/index.jsx, rconweb/api/audit_log.py
Adds pagination to the audit log query which was necessary because large tables would cause timeouts.
New parameters `page` and `page_size` which default to `1` and `10` respectively so it won't blow up if people don't pass them.
The SQL offset is `0` indexed, we account for that so people use `1` indexed page numbers, `1`, `2`, etc.
If you ask for a page # beyond the number of pages you'll receive an empty result `[]` instead of an error.
I have not touched the UI but I imagine it is pretty easy to integrate these changes.
=> Add pagination to audit log query

rcongui/src/pages/views/live/logs-columns.jsx, rcongui/src/pages/views/live/logs-table.jsx
Issue: Player filter works only for `This Player` column
Solution: The row is displayed if `searched player` is in either `this` or `that` columns
=> UI: Player filter works only for `This Player` column

rcongui/src/pages/views/live/TeamSelectionToolbar.jsx
Issue: Selecting players by rank in the `Live View` did nothing
Solution: The handleRankSelect function was never implemented.
**Please, test all other selects before approving the changes, cheers!**
PS. The handler shared common logic which was refactored into a generic function.
=> UI: Select players by rank

rcongui/src/features/player-action/actions.js, rcongui/src/features/player-action/forms/AddVipFormFields.jsx, rcongui/src/pages/settings/vip/index.jsx
Issue 1: Users cannot add additional text for the VIP description
Issue 2: Users cannot add "Never expires" VIP in the VIP settings view
Solution 1: Added `prefix` & `suffix` fields to the form with disabled example preview field
Solution 2: Added "Never expires" button & allowed very high date for the datetime field
=> UI: VIP Forms

rcongui_public/src/lib/utils.ts, rcongui_public/src/pages/games/[id]/layout.tsx, rcongui_public/src/pages/games/columns.tsx, rcongui_public/src/pages/games/horizontal-games-list.tsx
Currently is displaying the utc time. Also checked that sticky dates still work correctly.
I checked the old public stats page and moment automatically converted it to local when formatting.
=> FE: display local time

rcongui_public/src/components/game/statistics/game-columns.tsx, rcongui_public/src/components/game/statistics/game-table.tsx, rcongui_public/src/components/tag-list/index.tsx, rcongui_public/src/components/ui/checkbox.tsx, rcongui_public/src/components/ui/select.tsx, rcongui_public/src/i18n/locales/en/game.json, rcongui_public/src/pages/games/[id]/index.tsx, rcongui_public/src/pages/home/index.tsx
=> Add optional columns to public stats page

rcongui/src/pages/settings/vip/index.jsx
Hello,
this renames the expiration variable so the ADD_VIP Intend is working. 
This should only fix the date issue temporarly. The VIP upload needs to be reworked anyway to use the api endpoint for uploading.
=> UI Fix: VIP Upload, use correct variable name for expiration

rcongui/src/features/player-action/ActionMenu.jsx
=> depraceted != deprecated

rcongui_public/src/components/game/statistics/game-columns.tsx
=> FE: stats: making 'by category' columns wider

rcongui_public/src/pages/home/streaming/index.tsx, rcongui_public/src/pages/home/streaming/stream-banner.tsx, rcongui_public/src/pages/home/streaming/stream-tutorial.tsx
Store stream settings in local storage as obs refreshes browser sometimes -> loses settings
updated example css colors
=> FE: Streaming: store stream settings in local storage

rcongui/src/components/layout/AppNavbar.js, rcongui/src/components/layout/MenuContent.js, rcongui/src/components/layout/SelectContent.js, rcongui/src/components/layout/SideMenu.js, rcongui/src/components/layout/SideMenuMobile.js, rcongui/src/components/layout/sidebar/ReleaseNotes.jsx, rcongui/src/components/layout/sidebar/UserActions.jsx, rcongui/src/pages/root.jsx
- User is now able to change  theme and mode 
- User is now able to change password
- The sidebar hides on a link click
- On very small screens the sidebar has full width
- Removed margin from layout on small screens
=> UI: Mobile sidebar fixes

rcongui/src/pages/records/game-logs/index.jsx
The clear button wasn't working correctly
- Incorrect date onChange handling.
- Incorrect autocomplete onChange handling
Added new and correct onChange handlers
=> UI: Game Logs - fix search form

rcongui/src/components/layout/NavigationProgress.jsx, rcongui/src/pages/records/audit-logs/index.jsx, rcongui/src/pages/records/players/index.jsx, rcongui/src/pages/root.jsx
UX: Added global loading navigator when routing & submitting router based forms eg., records->players.
=> UI: Add global navigation progress indicator

rcon/watch_killrate.py
* The watch kill rate feature takes the KPM from player stats for its initial check but we weren't recalculating to properly account for whitelisted weapons
* This re-calculates a players KPM after filtering out any whitelisted weapons; otherwise their base KPM can trigger the embed even if a whitelisted category (armor, artillery, etc.) would not.
I did not explicitly test this because our server isn't populated right now but it should work; I'll test later once our server seeds but this should work.
=> Correct KPM calculation for watch kill rate

rcongui/src/components/layout/sidebar/About.jsx, rcongui/src/components/layout/sidebar/ReleaseNotes.jsx, rcongui/src/features/player-action/ActionDialog.jsx
Use `tag_name` property to determine whether the local build is the most recent version.
Display modal full screen on small screens.
=> UI: About modal version

rcongui/src/pages/records/players/[playerId]/index.jsx
* Avoids a crash on the player profile page
=> Include LocalizationProvider on the player profile comments page 

rcongui/index.html, rcongui/public/manifest.json, rcongui/src/hooks/useTemplates.js
=> fix: delete react logo link

rcongui/src/pages/records/players/[playerId]/styled.jsx
=> UI: Fix player profile page resize

rcon/watchlist.py
Add the server short name to the watchlist embed footer
=> Add server footer to watchlist messages

rcongui/example.env, rcongui/src/pages/login/index.jsx, rcongui/src/utils/fetchUtils.js, rcongui/vite.config.mjs
There was very stupid logic handling text/plain responses and if the response was of this type it always threw error.
While I was at it I managed to simplify the main request handling function.
=> Fix: User cannot download VIP files
