rcongui/package.json, rcongui/src/App.js, rcongui/src/components/Scoreboard/GamesScore.js
Allows for having persistent links to directly select a specific match, for instance http://62.171.172.221:7041/?map_id=3793#/gamescoreboard
This also adds a bar displaying the link that can be shared to reference the currently selected map, as well as a button to directly copy it.
One flaw. When a map id is specified in the URL it has to fully redirect the user to a URL with the new ID.
=> Add a map_id parameter to the gamescoreboard URL

Dockerfile-frontend, Dockerfile-frontend-arm32, Dockerfile-frontend-arm64
This is faster and [recommended by NPM](https://docs.npmjs.com/cli/v7/commands/npm-ci) for automated build processes
=> Use npm ci to install JS deps

Dockerfile-frontend-arm32
The React build process runs out of memory on small systems with the default settings. Skipping sourcemap generation saves a lot of memory, allowing the process to complete on these arm32 devices which typically have only 2 gigs of RAM.
=> Skip sourcemap generation on arm32

rcon/discord_chat.py, rconweb/api/views.py
Running this endpoint and passing a `command` parameter will return the response returned by the game server in plain text without attempting to parse it (eg. in case of an array). If an internal error occurs the stack trace is printed out.
This makes it easier to investigate why a command failed, but may also be used to fix server misconfigurations that are preventing it to be done through the regular API, for instance if a ban reason contains a tab.
And apparently there's some small changes still left on the same branch from a while ago that adds some small details to the embed which was requested by someone who wanted to send the chat logs of multiple servers into the same channel.
=> Add GET run_raw_command endpoint for debugging purposes

Dockerfile-arm32
fix building docker image for armhf by installing rust via rustup instead of apt
it failed on building the python module "cryptography"
=> fix building docker image on armhf

Dockerfile-arm64
fix building python "cryptography" module by installing rust via rustup
=> fix building docker image on aarch64

rcon/commands.py, rcon/extended_commands.py, rcon/squad_automod/automod.py
After quite a lengthy investigation we found that the game server returns data for a player different than the one you made a query for. This is a workaround to make the command fail in case it happens.
=> Work around for game server returning wrong player data

rcongui/src/components/Scoreboard/Scores.js
Add the steam ID 64 column to the scores table as requested in https://github.com/MarechJ/hll_rcon_tool/issues/120
Resolves #120
=> Add steam ID to scores table

rcongui/src/components/Scoreboard/Scores.js
JSON stringify any column values that are objects leaving non-object values untouched.
e.g. "[object Object]" will show as ""{""WALTHER P38"":1,""GEWEHR 43"":1,""FELDSPATEN"":1}""
=> JSON stringify object column values

rcongui/src/components/LogsHistory/logsHistory.js
The player name parameter was incorrectly set to `this.statename` rather than `this.state.name` causing the historical log CSV download to not filter by player name. The data table would show the correct results but on downloading the resulting POST request would return results for all players.
I tested the change on our event server that has access to historical data and it appeared to work correctly.
=> Fix historical log download parameter typo

README.md
when doing my initial setup  i couldnt connect to the db
after some digging i found that my HLL_DB_PASSWORD contained # which broke the code to connect to the db
sofar i found that # and % break it
most ideally this should be also included in .env but it doesnt make sense to change .env for such minor changes
for the changes to .env i would propose a second pr that gets merged before meaningful changes are done to .env
=> add info about characters that break db connection to readme

rcon/game_logs.py
When filtering log lines by players, when selecting two players the log line would appear twice, once for each player in the log line.
Did a clean build from a freshly pulled repository and tested it successfully on our event server.
=> Fix bug where the same log line would appear twice

config/supervisord.conf
Scorebot depends on the backend being started and responsive but starts much more quickly than the backend does.
With 10 attempts scorebot will always end up in a fatal state on an RCON restart or initial start.
Increasing restart attempts to 24 will allow scorebot to start automatically when starting/restarting RCON, it will attempt to start for ~5 minutes with the progressive back off times used by supervisord.
[As documented here](http://supervisord.org/subprocess.html#process-states) 
> Retries will take increasingly more time depending on the number of subsequent attempts made, adding one second each time.
>
> So if you set startretries=3, supervisord will wait one, two and then three seconds between each restart attempt, for a total of 5 seconds.```
I tested the change on our server …
```
=> Increase restart attempts for scorebot service

rcon/extended_commands.py, rcon/scorebot.py, rcongui/src/components/Embeds/ServerInfo.js, rcongui/src/components/Scoreboard/LiveScore.js, rconweb/api/views.py
Include the newly available information (via the `gamestate` command) into the data returned by public_info.
Unfortunately the `time_remaining` does not really contain useful information (not even sure what the game-server will return for this value on offensive maps).
Therefore the cumbersome way of loading the start time of the current map via the MapsHistory is still included.
Furthermore redundant fields are removed and additional information for the `next_map` is included.
Removed the `nb_players` field and instead added the `max_player_count` field.
=> Clean up and adapt public_info for new data

rcongui/entrypoint.sh
it's either bash:
```
[[ ! -f "/certs/cert.crt" || ! -f "/certs/key.key" ]]
```
or shell:
```
[ ! -f "/certs/cert.crt" ] || [ ! -f "/certs/key.key" ]
```
but not a combination of both.
=> Fix frontend entrypoint

rcon/hooks.py, rcon/vote_map.py
On a match start event, vote map is initialised and applied. Applying vote map settings should, however, only be done when the vote map feature is actually enable.d
=> do not overwrite map rotation with vote map when vote map is not enabled

config/auto_settings.default.json
This will reduce confusion for users setting up CRCON in the future.
Users that have it already set up will be confused, since they probably have the default config still included in their autosettings (at least we do) which indicates another variation of the `set_maprotation` command.
[Regarding this commit](https://github.com/MarechJ/hll_rcon_tool/commit/8ed7dd278dfc8f24183a0b9f91df6dbfcf98d1bc)
=> Adjust auto settings default to be inline with changed command

config/auto_settings.default.json, rcon/auto_settings.py, rcon/vote_map.py
This allows to restrict the available maps for votemap via the autosettings.
The logic for storing and accessing the whitelist has been tested, but I am currently unable to test the whole package against a server. Although I think it should be fine™
This is only a "backend" implementation and does not contain a rotation manager like GUI to modify the whitelist. I am just not fluent enough in React to implement this in a reasonable time. Not even sure if it would be used by anyone.
Furthermore the code does not perform tests in order to avoid an empty selection.
We could maybe fallback on `pick_default_next_map` in case this happens (and ignore the whitelist as is currently)?
=> Implement whitelist logic for votemap via autosettings

requirements.txt
Bump `rq` version to `rq~=1.11.0` for click 8.x.x compatibility
=> Bump rq version for click 8.x.x compatibility

rcon/auto_settings.py, rconweb/api/history.py
In the current iteration the request `/api/player?steam_id_64=76543219876543210&nb_sessions=20` does not work since the provided `nb_sessions` value is interpreted as string
=> Fix get player

rcon/player_history.py
Hooks might be called twice (when the log event loop crashes or gets restarted for another reason while processing hooks). There should never be a reason to save the same player session twice, anyway.
=> Do not record duplicated player sessions

rcon/automods/automod.py
In rare cases, the rcon tool might not yet recognized that the server reached enough population to disable seeding rules (something around 2-7 seconds, depending on how long it takes for the first call to get_team_view).
Kills during this time are handled by an event, while the seeding automod assumes the server did not reach the seeding threshold yet. This might result in kills being punished as they were made with a seeding-disallowed-weapon, despite the server having enough players.
This commit fixes this by giving automods generally a bit of time after restaret of the rcon tool to warmup. This might defer or miss enforcements on some kills, but at least no-one is punished wrongfully.
=> Fix rcon mod wrongfully considering kill as "during seeding"

Dockerfile-frontend, Dockerfile-frontend-arm32, Dockerfile-frontend-arm64, rcongui/entrypoint.sh, rcongui/nginx.conf
Locally, the multi-stages are still cached, the resulting image size is reduced (on my machine) from 1.6 GB to around 75MB.
I tested the amd64 image, only, not the ARM ones, however, they should be fairly the same, if anyone else can test them, though? 🤔
=> Reduce resulting image size of frontend image by utilising multi-stage build

rcongui/src/components/GameView/index.js
When the team_view takes longer than the configured refresh interval, it might result in requests to server piling up. As this is pretty pointless, simply wait until the response is there and _then_ schedule the next interval.
=> do not load new team_view before time after "old" team_view request expired

rcon/commands.py
Otherwise, a connection is returned to the pool with still having data that is not read from the socket, or it tries to read data from a command of one connection from a new connection, which cannot work :D
=> When reading log list, use the same connection (where the data resides)

rcon/commands.py
When the game server returns a FAIL, this usually does not mean that the connection itself is broken, hence it should not be discarded.
This also fixes the set_map logic that ensures that the map is in the rotation if changing the map fails.
=> Do not throw away connection on FAIL

rcon/automods/automod.py, rcon/automods/seeding_rules.py
A global variable set during an automod run is not available when en event from the log event loop is processed. Save this shared state in redis instead.
Also make announcement work when only disallowed roles is configured.
=> Fix announcing seeding rules on connect

rconweb/api/auth.py
Update the moderator account feature to use the correct Django `app label`.
https://docs.djangoproject.com/en/4.1/ref/contrib/auth/#django.contrib.auth.models.User.has_perm
`User.has_perm()` returns False by default and since we're testing the inverse permission this was silently failing.
Built an image and tested it against our event server and it would no longer let me add VIPs so this appears to fix it, I did not do any in-depth testing to verify setting by setting though.
=> Fix reduced permissions moderator accounts

rcon/config.py
Print the actual YAML validation error when loading invalid YAML so users can troubleshoot easier.
For example:
```
[2023-03-03 19:26:43,343][ERROR] rcon.config config.py:get_config:39 | User config at '/config/config.yml' is invalid YAML
[2023-03-03 19:26:43,343][ERROR] rcon.config config.py:get_config:40 | while scanning for the next token
found character '\t' that cannot start any token
in "/config/config.yml", line 329, column 38
```
=> Print the YAML validation error for easier troubleshooting

rcon/game_logs.py
Convert milliseconds to seconds, Python will currently throw a `ValueError` because it exceeds the maximum date allowed (on top of being the wrong datetime anyway).
Built and tested on our event server and it does ban people properly now.
=> Convert milliseconds to seconds properly

config/default_config.yml, rcon/automods/automod.py, rcon/automods/models.py, rcon/automods/no_leader.py, rcon/automods/seeding_rules.py, tests/test_seeding_rules_automod.py
A new seeding rule that, when configured, warns/punishes players who gain offensive points when their team is "winning" (has the amount of caps configured in the config), which is considered "attacking the enemy sector".
=> Enforce Cap Fight during seeding

rcon/automods/no_leader.py
`from rcon.types import GameState` is the only change, the rest is formatting.
Was broken because we didn't import the type. Tested it against a live server and it runs.
=> Fix missing import

rcon/models.py, rcon/scoreboard.py, rcon/types.py, rcon/workers.py, rcongui/src/components/Scoreboard/Scores.js, rconweb/api/scoreboards.py
This was a feature request I recently got multiple times (and found myself as well). Instead of just showing with what weapon a player made their kills, it is also of interest with what weapon they were killed the most (e.g. artillery, MGs, etc).
As this is pretty cheap (from a calculation point of view) to implement, let's simply add it :D
=> Show with what weapon a player was killed

rcongui/src/components/Scoreboard/Scores.js
This commit alsoc hanges the default visibility of the steam ID column to false. This info is mostly not needed, except people really want to show it. On the other hand, the column is pretty wide and takes huge amount of space in the table, which is already pretty crowded.
Filtering by steam ID is also possible when the column is not displayed, so this should be fine.
=> Show and allow to filter by steam ID on scoreboards

rcon/scoreboard.py
There was a typo so disconnects were never being processed when accumulating streaks.
L66-68 are only formatting changes.
Built and tested it against a game server and it works. I've occasionally seen goofy times for stats and I suspect this was causing it.
=> Fix streaks calculation when players disconnect

rcon/recorded_commands.py
The only real change is line 263, the rest is formatting from `black`.
Adds the ability to message players to the `@mod_users_allowed` list of commands.
=> Add player messaging to moderator accounts

rcongui/src/components/PlayersHistory/index.js
Don't load automatically on page load for users with giant databases where queries are slow.
I did test this locally and it works fine.
=> Don't load player histories on page load

rcongui/src/components/Scoreboard/PlayerStatProfile.js, rcongui/src/components/Scoreboard/SubList.js
Including the `death_by_weapons` in the raw stats sublist is not a good idea as can be seen in the screenshot.
Move those stats into their own sublist and make the sorting of the entries in the raw stats list consistent (sort by key instead of value)
=> Move death_by_weapons in own sublist and consistent entry sorting

.env, default.env, docker-compose-common-components.yml, docker-compose.yml
Turn the Docker hub repository and version into a `.env` environment variable so people don't need to edit the docker-compose files to upgrade or downgrade versions.
I tested it and I was able to pull images just fine with it.
If we want to do this we should hold off on the merge until we're ready to make any other `.env` changes we want, like deprecating the steam stuff if we merge PR 279 for instance.
=> Make docker repo and version a .env variable for easier downgrades

rcon/rcon.py
Use the `next_map` result from the gamestate command to return the next map instead of guessing it based off rotation.
=> Use the gamestate command to get the next map

docker-compose.yml
Swap the `redis` and `postgres` images to their `alpine` equivalents for reduced file size.  Saves about 275mb which isn't insignificant.
I built this and while I did not exhaustively test it it works like normal as far as I can tell.
=> Use alpine redis/postgres images for smaller file sizes

rcon/connection.py
Increase the buffer size from 8,192 to 32,768 bytes. This aligns on a power of 2 (as the docs recommend) and should reduce the number of incomplete requests we get due to HLLs RCON protocol limitations.
=> Increase TCP socket buffer size

rcon/rcon.py
Whoops, I messed up when combining extended/recorded RCON and `get_players` would not return any players that did not have a profile.
Tested it against our live server and it works correctly now.
=> Don't skip players when they don't have a profile

rcon/rcon.py
Missed this when merging extended/recorded RCONs
=> Add missing player cache invalidator

rcon/hooks.py, rcon/rcon.py
Fixed correctly this time, built and pointed it at our server and verified that it does not throw errors when players connect.
`handle_on_connect` in `hooks.py` was checking if it was an instance of `RecordedRcon` and then using that method to clear the cache, if it was `Rcon` (`extended_rcon.py`) then it was trying to call `rcon.get_player.cache_clear`, but that doesn't (and didn't exist as far as I can tell) exist lol, so that method and that check don't need to exist now that the two classes are merged.
All we have to do is nuke `invalidates_player_list_cache` and just directly clear the cache in `hooks.py`.
=> Properly fix cache invalidation when players connect

rcon/rcon.py
I was in the middle of trying to type stuff so I could understand stuff better/use pylance more while merging extended/recorded Rcons, forgot to finish.  Reverts to the previous working version that was in `v7.2.1`
=> Revert unfinished typing change; vip status/profile was missing

rcon/automods/level_thresholds.py, rcon/automods/seeding_rules.py
Seems these attributes were forgotten, causing an automod service restart everytime a player can't be punished.
Fixes :
- "AttributeError: 'SeedingRulesAutomod' object has no attribute 'player_punish_failed'"
- "AttributeError: 'LevelThresholdsAutomod' object has no attribute 'player_punish_failed'"
=> Fixes an "AttributeError: 'SeedingRulesAutomod'/'LevelThresholdsAutomod' object has no attribute 'player_punish_failed'"

config/auto_settings.default.json, rcon/user_config.py
Hey everyone,
first, thank you for this great software!
I have noticed that the command "set_map_shuffle_enabled" is missing in the standard configuration for autosettings. Since the standard configuration serves as documentation, I think it makes sense to include this command in the file. In this pull request I have done exactly that. This should make it easier for new users (including me) to include it. 
Thank you very much!
=> Autosettings: Add "set_map_shuffle_enabled" to default config

rcon/utils.py, rconweb/api/views.py
* Add server number to get_connection_info endpoint
* Login is already required, and the server number doesn't seem like particularly privileged information
* Had a user request this
Output would look like:
```json
{
"result": {
"name": "Saucymuffin's [BEER] Haus & Squidd Cafe Part Deux",
"port": "8010",
"link": "http://localhost:8010",
"server_number": "1"
},
"command": "get_connection_info",
"arguments": null,
"failed": false,
"error": null,
"forwards_results": null
}
```
=> Add server number to get_connection_info endpoint

config/default_config.yml, rcon/automods/automod.py, rcon/automods/models.py, rcon/automods/no_solotank.py, tests/test_no_solo_tank_automod.py
Watches and warns/punishes/kicks the solo tankers SLs
(non-SLs are already managed by "no leader watch").
The armor squads usually come in crew.
But a player may open an armor squad and wait for his mates to enter.
So the automod won't do anything during the X first minutes ("note").
Then, based on configuration, it will begin a standard automod cycle (warn X times, punish X times, kick).
Based on the "no leader watch" automod.
=> No solo tank automod

rcon/rcon.py, rcon/vote_map.py
The current TTL on many cached RCON commands pretty much assume that the CRCON is the only tool used, which in practice is often far from the truth. This PR makes it a bit more lenient in that regard, making cached values expire sooner.
Also includes a quick change that disables the "Votemap is disabled" message when using !votemap on a server that doesn't use it - that way other tools can implement their own map voting without players getting a message telling them map voting is disabled.
=> Improve compatibility with other tools

rcongui/src/components/PlayersHistory/PlayerTile/PlayerBan.js, rcongui/src/components/PlayersHistory/index.js, rcongui/src/components/PlayersHistory/playerGrid.js
Adds a players ban (temp, perma or both) status to the player info cards shown on the `History > Players` page.
I'm pretty bad with Javascript/HTML so there might be a better way to do this.
I kept the ban position (perma on the right, temp on the left) instead of letting it flow/align, so that it's easier to identify the type of ban while scrolling quickly.
I had to bump the player card size up a few pixels so that the content wouldn't overflow.
=> Show ban status on player history card

rconweb/api/views.py
I am not sure what I was thinking when I originally wrote this.
Only require the actual change map permission to let users change the current map.
It is just a one line change but I did build it, make a test user and verify that it works.
=> Require only the change map permission to change maps

rcon/vote_map.py
I've added a "!vm" command, considering a lot of players seem to miss votes, either because they're too lazy to type in chat, either because they make typos in the "!votemap" command (ie : "!votmap", "!vote map", "votemap", etc).
Now you can either use the regular "!votemap" or the shortened "!vm" command.
Tested today on a full server with no apparent prob.
=> Short votemap chat command

tests/test_ban_tk_connect.py
I forgot to update this when we merged extended/recorded Rcons into a single class.
=> Fix mock patching class name

rcon/rcon.py
* Add the server number to the `get_status` endpoint
`get_status` is locked behind a permission and you have to be logged in and I don't think the server number is sensitive information.
Output looks like:
```json
{
"result": {
"name": "Saucymuffin's [BEER] Haus & Squidd Cafe Part Deux",
"map": "elalamein_warfare",
"nb_players": "0/100",
"short_name": "MyServer",
"player_count": "0",
"server_number": 1
},
"command": "get_status",
"arguments": {},
"failed": false,
"error": "",
"forward_results": null
}
```
=> Add server number to get_status endpoint

rconweb/api/auth.py, rconweb/api/urls.py
* Add `get_own_user_permissions` endpoint to show a logged in user their user permissions and whether or not they are a super user (allows access to all endpoints regardless of permissions).
Output looks like
```json
{
"result": {
"permissions": [
{
"permission": "can_add_admin_roles",
"description": "Can add HLL game server admin roles to players"
},
{
"permission": "can_add_map_to_rotation",
"description": "Can add a map to the rotation"
},
{
"permission": "can_add_map_to_whitelist",
"description": "Can add a map to the votemap whitelist"
},
{
"permission": "can_add_maps_to_rotation",
"description": "Can add maps to the rotation"
},
{
"permission": "can_add_maps_to_whitelist",
"description": "Can add multiple maps to the votemap whitelist"
},
{
"permission": "can_add_player_comments", …
```
=> Add an endpoint to show a user their permissions

rcongui/src/components/AuditLog/index.jsx, rcongui/src/components/LogsHistory/logTable.js, rcongui/src/components/LogsHistory/logsHistory.js, rcongui/src/components/PlayerInfo/PlayerInfo.js, rcongui/src/components/PlayerView/playerList.js, rcongui/src/components/PlayersHistory/PlayerTile/PlayerPenalties.js
Instead of using mixed UTC and local times, the frontend should use one timezone consistently. As local seems to be the more natural thing, I choosed to change all time usages I could find to the local timezone.
This includes the log view, which might be the most visible change with this commit (the time in the log view was UTC so far).
=> Always use local time zone in frontend

rconweb/api/history.py, rconweb/api/urls.py
* Add `get_previous_map` endpoint to show the last recorded map end.
No permission for it, except it's locked behind the public stats thing, and anyone with public stats already exposes their match history.
This was user requested to support a tool.
Output looks like (will return `None` if there is no map history):
```json
{
"result": {
"name": "stmariedumont_warfare",
"start": "2023-10-23T14:45:34",
"end": "2023-10-23T14:46:50"
},
"command": "get_previous_map",
"arguments": null,
"failed": true,
"error": null,
"forwards_results": null
```
=> Add previous map endpoint

rconweb/api/auth.py, rconweb/api/models.py
Whoops. Didn't account for `KeyError`s when the authorization headers are missing.
Noticed this while keeping my UI settings branch up to date, this fixes it.
=> Fix key errors when authorization headers are missing

rcon/rcon.py, tests/test_logs.py
* Handle kick types of the variety: `[3:41 min (1699465895)] KICK: [Elinho] has been kicked. [Kicked for failing auth]`
* Parse future kick types that we haven't seen yet
* Both of these are collected under `ADMIN MISC` as the action, I asked T17 what this means, I did not receive a clear answer but it is *probably* an EAC thing.
* Added new log parsing tests, they pass.
=> Capture new kick type, handle future new kick types

requirements.txt
* While merging updated requirements on other branches, I accidentally removed `rq-scheduler`
* Downgrades `rq` because newer versions are incompatible with the version of `rq-scheduler` we're using, it tries to import something that's deprecated
=> Downgrade rq, re-add missing rq-scheduler

rcon/automods/automod.py, rcon/automods/seeding_rules.py
**Prevents the automod.log file size to skyrocket**
By default, **automod includes in its log ALL the messages** the involved players have received **since they entered CRCON's base**. This behavior can rapidly generate a multi GB logfile if you're using a lot of automatic messages (votemaps, automods, custom scripts that send games stats, etc) on your server.
Most of the CRCON users won't notice this problem, as the log rotation caps the file size limit to 10MB.
=> Log automod less verbose

rcon/models.py, rcon/types.py
Fixes almost all of the typing issues we had in `rcon/models.py` and removes some redundant explicit things we no longer need now that we're on sqlalchemy 2.x
=> Cleanup model typing, remove redundancies

rcon/discord_chat.py
The length method needs to be fixed upstream, I disabled the debug statement for now as it's not needed.
=> Disable logging with broken len

rcon/types.py
* Fixes a typo (users weren't impacted) for `cxis_chat`
* Adds all log types (this was missing some of the synthetic types) so users can use them with `Log Line Webhooks`
=> Add all log types and fix typo

rcon/commands.py, tests/test_utils.py
* Convert tabs to a single whitespace for the commands that accept arbitrary user input that are stored by HLL as tab delimited lists to prevent broken lists/failed get commands
* do_ban_profanities
* do_temp_ban
* do_perma_ban
* do_add_admin
* do_add_vip
https://gist.github.com/timraay/5634d85eab552b5dfafb9fd61273dc52#lists
=> Strip tabs from commands accepting end user input that are lists

rcon/hooks.py, rcon/types.py, rcon/user_config/rcon_server_settings.py
* Properly handle `None` type actions for invalid names
I originally put the `None` action into the `RconInvalidNameActionType` enum which doesn't work properly because it's serialized to a string in JSON.
This updates the model to either be a `RconInvalidNameActionType` or `None` otherwise it throws errors when trying to save a default model, which is not great.
I built this and tested it against a live server with both whitespace/pineapple names.
=> Handle invalid name none actions properly

rcongui/src/components/AuditLog/index.jsx, rconweb/api/audit_log.py
* Convert the `get_audit_logs` endpoint to require `GET` not `POST`
* Update the GUI to call it correctly
Built it locally and did some quick minimal testing and it filters correctly.
=> Convert get_audit_logs endpoint to GET not POST

rcongui/src/components/Header/serverStatus.js, rconweb/api/views.py
* Fix the `get_connection_info` which wasn't properly returning `null` when `RconServerSettingsUserConfig.server_url` was `None`
* Fix the GUI which would endlessly add extra `/` characters to the URL when swapping between servers
Manually tested this on a local build connected to two servers, both without `server_url` set and with, seems to work just fine.
=> Fix URL for server swapping and `get_connection_info` endpoint

rcongui/src/components/PlayersHistory/index.js
* Allow the player history grid to add or remove a watch from a player with no name
You can add a watch to a player with no name from the settings page, but the player history grid would throw an exception when trying to access the players name since they don't exist.
Built/tested it locally and it works fine.
=> Don't crash when watch/unwatching a player with no name

rcon/player_history.py
* Don't attempt to record the end of a session that doesn't exist
If a player disconnects, but CRCON was not running when they joined to have a session created in the first place, it throws an exception.
=> Fix last session recording when no session

rcon/rcon.py, tests/test_logs.py
* Update log parsing to capture `prematurely` expired vote kicks, whatever the hell those are
* Update tests
Example: 
```
logs/log_event_loop_1.log:[2023-12-22 21:26:33,801][ERROR] rcon.rcon rcon.py:parse_logs:1562 | Unable to parse line: '[2:14:33 hours (1703272319)] 1703272319 VOTESYS: Vote [3] prematurely expired.'
```
=> Parse prematurely expired votekicks

rcon/game_logs.py, requirements.txt
At some point in the last day or so Discord stopped accepting allowed mentions as a list and now requires them to be passed as a dict.
https://discord.com/developers/docs/resources/channel#allowed-mentions-object
We're also not using any of the modifications I made on the fork of `discord_webhook` so I've reverted it to the upstream version.
Tested this and it works just fine now.
=> Pass allowed mentions as a dict not list due to discord API changes

rcongui/src/components/PlayerInfo/PlayerInfo.js
A user requested that the steam profile be linked from the detailed player profile page. This will generate junk links for windows store ID players, but that's true of the steam profile links on the player history page too.
Now looks like:
=> Link steam profile from detailed player page

rcon/player_history.py, rcon/rcon.py
As identified by [KL 彡 Fw.Schultz](https://discord.com/channels/685692524442026020/685695097349734469/1189923485238169743) when a VIP file was uploaded, but the player had never been on the server their expiration date would not be set correctly.
* Create a PlayerSteamID record if `do_add_vip` tries to add VIP to a player without a record
* Simplify setting VIP expirations
I built this, verified it works correctly when uploading a file and when an expiration date is set through the GUI. Expired VIPs are still pruned correctly when the service runs.
=> Fix VIP expiration dates when no player steam ID record exists

rcongui/src/App.js
Django and React were both using the same theme name, and the Django admin site would reset the theme to `auto` if it didn't recognize a theme name.
This will reset everyones themes to default when they upgrade, but it will stop resetting the themes when people use the admin site and it's trivial to set their theme again.
=> Avoid theme name collision with Django admin site

rcon/rcon.py, rcon/steam_utils.py, rcon/utils.py, tests/test_logs.py, tests/test_steam_utils.py, tests/test_utils.py
* Update the kill/team kill log parsing regex to support windows store IDs
* Refactor the player info command result parsing for easier testing
* Update various steam utilities to only call the steam API if the player ID is an actual steam ID
* Add various tests
I did build this, run the tests (some of the tests fail but it's unrelated to this and should be failing on master as well), assign a steam API key and connect it to a server with actual players on it and let it run a bit and poked around, I believe this works correctly.
I am curious/suspect there might be a better way to do the filtering decorators and I am all ears.
I do have to fix some cache handling errors from #410 but you'll only see that issue if redis is unavailable, and docker desktop (where I almost exclusively do this …
=> Update backend to support windows store player IDs

rcon/rcon.py
In some scenario(s) it is possible to end up with an empty map rotation (I haven't investigated that part), which will cause `set_maprotation` to fail:
```
[2024-01-03 16:12:45,899][INFO] rcon.rcon rcon.py:set_maprotation:1346 | Current rotation: []
[2024-01-03 16:12:45,899][ERROR] rcon.auto_settings auto_settings.py:do_run_commands:202 | Unable to apply set_maprotation {'rotation': ['remagen_warfare', 'carentan_warfare', 'stmariedumont_warfare', 'hurtgenforest_warfare_V2', 'foy_warfare', 'utahbeach_warfare', 'stmereeglise_warfare', 'purpleheartlane_warfare', 'hill400_warfare', 'omahabeach_warfare']}
Traceback (most recent call last):
File "/code/rcon/auto_settings.py", line 200, in do_run_commands
rcon.__getattribute__(command)(**params)
File "/code/rcon/rcon.py", line 1357, in …
```
=> Don't cause IndexError's when current rotation is empty

rconweb/api/admin.py, rconweb/api/auth.py, rconweb/api/models.py
Django doesn't allow the `$` character in salts when hashing passwords, it's acceptable in the `SECRET_KEY` that we're using as our salt value to ensure API keys are hashed/unhashed to the same value.
Strip the `$` key anywhere it's used in the salt, this doesn't affect `SECRET_KEY` in any way and Djangos `SECRET_KEY` rules for length/minimum unique characters mean there should still always be characters left over in the salt no matter what.
I built this and made sure I could add API keys from both the API key management view in the admin site and the individual user page and was able to authenticate against the API with it with a `SECRET_KEY` that included `$`.
=> Strip `$` characters from the secret key as it's not allowed in the salt

rcon/auto_kick.py, rcon/automods/automod.py, rcon/game_logs.py, rcon/hooks.py, rcon/models.py, rcon/player_history.py, rcon/rcon.py, rcon/steam_utils.py, rcon/types.py, rcon/utils.py, rcon/watchlist.py, tests/test_steam_utils.py
It's hard to say for sure since this involves external services, but I think this should cut down or maybe even eliminate users being rate limited by the Steam API. Previously, clearing the redis cache could also cause CRCON to hammer the steam API a bit since it would call it every time `get_players` was called (very often) until the values were re-cached, this avoids that.
I did build this, let it run, did quite a bit of poking around/manual testing and I don't believe I've changed the API results or broken anything.
This should cut down how often the steam API is called, but if a lot of `on_connected` hooks are processed at once (for instance you reconnect your CRCON to a game server that has been offline and it reprocesses a lot of old log lines at once), and of course rate limits …
=> Refactor steam API usage to try to reduce rate limiting

rconweb/api/auth.py, rconweb/api/multi_servers.py, rconweb/api/views.py
Forwarding when authenticating via an API key was broken.
`forward_command` was also still using `GET` requests by default and not `POST`
Built and tested this via our 2 servers, verified it would forward correctly when using both the UI and API calls when authenticating via API key.
=> Fix forwarding with API keys

rcon/models.py, rcon/types.py
VIP status wasn't reflected on the `profile` endpoint (ex: https://example.com/#/player/76561198004895814)
It now shows as a list of the servers they have VIP on and their expiration timestamps. It isn't perfect as it relies on `PlayerVIP` records, so players can have VIP on the game server but without a record. `PlayerVIP` records are created when VIP is added through `rcon.do_add_vip`  or when the expiring VIP service runs (hourly by default)
```json
"vips": [
{
"server_number": 1,
"expiration": "3000-01-01T00:00:00Z"
}
]
```
=> Add VIP info to PlayerVIP `to_dict`

rcongui/src/components/PlayerInfo/PlayerInfo.js, rcongui/src/components/PlayerView/playerList.js, rcongui/src/components/PlayersHistory/PlayerTile/PlayerHeader.js, rcongui/src/components/Scoreboard/PlayerStatProfile.js, rcongui/src/utils/makePlayerProfileUrl.js, rcongui/src/utils/makeSteamProfileUrl.js
Add support for win-store playerid "profile" links.
Win-store playerids will link to an xboxgamertag.com search. This is a third-party site, but Microsoft does not have a player lookup web service that can be used. Note that gamertags are unique and cost money to change so gamertags should be more stable than steam player names.
- update `makeSteamProfileLink` to detect steam vs. win-store playerids + return appropriate url
- update live views to use `faWindows` icon for win-store playerids
*`faWindows` icon:*
*Old screenshot (no win-store players the last few days):*
=> Add support for win-store playerid "profile" links.

rcon/discord.py, rcon/discord_asyncio.py, requirements.txt, tests/test_discord_asyncio.py
Add support for async discord webhooks, allowing handling of discord rate limiting.
Support is via a singleton class that creates an asyncio event loop in a new thread.
Use `DiscordAsyncio().send_webhook(hook)` to send an existing `DiscordWebhook` asynchronously. The fields in `hook` will be copied to a new `AsyncDiscordWebhook` before being sent.
Currently only used in `send_to_discord_audit()`, mostly because it rate-limits hard when using https://github.com/cemathey/hll_seed_vip.
=> add support for async discord webhooks

rcongui/src/components/LogsView/logs.js
The highlight logs toggle was defaulting to enabled on page load or refresh because we weren't casting it to a bool when retrieving it from local storage.
Line 128 is the only actual change the rest is formatting from prettier.
=> Cast logs_highlight_logs to a bool

rcongui/src/components/PlayerView/playerView.js
This function was defined twice and would throw annoying errors during the build process (credit goes to @caranci).
It doesn't hurt anything but it does clutter the build output with nonsense, I built and launched it against a live server and nothing changes (of course)
=> Remove duplicate function

requirements.txt
This used to be true but isn't anymore. I built and verified the supervisor service starts correctly.
=> Remove old comment that no longer applies

rcon/settings.py, rconweb/api/auth.py, rconweb/api/views.py, rconweb/rconweb/settings.py
Including the version in output should make it a lot easier to help people troubleshoot their problems, especially when people are running an older version where a problem is already fixed.
* Standardizes the logging format between the `rcon` and `rconweb` packages
* `rcon` logging wasn't including the server name
* Use the server short name as configured instead of the server name returned by the game server
* Include the tagged version in log files
* Include the tagged version in API responses
Example output:
`api_1.log`:
```
[2024-04-09 21:41:24,792][WARNING][MyServer1][v9.6.2] rconweb auth.py:is_logged_in:120 | admin's steam id is not set 
```
`startup.log`
```
[2024-04-09 21:51:10,482][INFO][MyServer1][v9.6.2] __main__ seed_db.py:seed_default_config:42 | Seeding DB
```
`get_status`: …
=> Include tagged version in logging/API calls

rconweb/api/votemap.py
This fixes the last lingering issue with `Layer`s not serializing to JSON correctly.
I also realized I accidentally changed the API output on an earlier PR (returning serialized `Layer` objects instead of the string map names).
We do want to change that down the line but that was accidental.
I explicitly sat down with `Postman` and hand tested each votemap/whitelist endpoint and I believe everything is working as intended now.
=> Fix serialization errors

rcon/hooks.py, rcon/maps.py
Use `UNKNOWN_MAP_NAME` when there are issues recording the map name instead of `bla_`.
This was causing errors with the `get_scoreboard_maps` endpoint and cause the entire command to fail once it hit a map that was recorded with `bla_`.
I didn't explicitly build/test this but it's a simple change.
=> Use existing UNKNOWN_MAP_NAME when we can't properly record the map name

rcon/maps.py, tests/test_maps.py
`_parse_legacy_layer` would fail when trying to parse map names set to `unknown` because of the missing trailing `_`
* Adds a test for parsing that style map name into a Layer
* Sets the map name/mode to `unknown`
This should preserve the other things that depend on map names being set to `unknown` like UI stuff and the map picture for it.
=> Handle parsing UNKNOWN_MAP_NAME as a Layer

entrypoint.sh, rcon/utils.py
I deleted this line when doing the Docker change up and that was a mistake, I misunderstood what it was doing.
This was preventing the server drop down list (when you click the server name in the header in the UI) from working and likely (but I didn't explicitly test it) breaking forwarding requests from one server to another.
=> Fix server list / forwarding

rcon/scorebot.py
Adds the newer maps to the scorebot look up.  I cycled through some different maps on our event server, seems like it works fine.
This is very much a bandaid, eventually we'll swap over to using the `Layer`s and things will know their own map image name and we won't have to manually update it.
=> Update map picture lookup

rcon/automods/seeding_rules.py
The documentation mentions max players in seeding automod to be exclusive, but the code handled it inclusive. This commit aligns the code to the documentation again.
=> align max players of automod to documentation

rcon/game_logs.py, rcon/scoreboard.py, rcon/types.py, rcon/workers.py
Previously, when a player disconnects and then reconnects to the server the stats gained in the previous session where lost. The CRCON would always only save the 'higher' stats value to compensate this a bit, which was far from perfect.
With this commit, the CRCON will try to salvage the previously gained stats and combine them after the round ended.
=> Salvage stats when player reconnects

rcon/game_logs.py
Fixes TypeError: cannot unpack non-iterable NoneType object when server has be idle in the log stream. 
The scenario occurs when last_seen is None and the tail returns None
=> Fix error in log stream when server is idle

rcongui/nginx.conf
Before this commit, the "biggest" asset of the frontend, the javascript, was not compressed, even though compression was enabled. Enabling compression for the actually used javascript mime type variant reduces the initial payload that nneeds to transferred from 3.7 MB to "just" 1 MB.
Note: Sorry for the indentation changes in the diff :(
=> Properly compress frontend assets

rcon/automods/seeding_rules.py
Updated gamemode checks by seeding automod to use the new Layer system to make it easier to maintain going forward.
Also makes sure the latest batch of Skirmish maps will cause cap enforcement to be disabled which wasn't yet the case.
=> Fix seeding automod not using new layer system

rconweb/api/auth.py
Hello,
currently the CRCON does not check when using the Stats API if an API key is used and the API is locked for the public in the CRCON settings.
This leads to "You must be logged in to use this" errors.
This PR introduces that the API key is also checked. I have used the source code of "login_required" for this. 
Is it perhaps smarter to outsource the code to an extra function? But because of two occurrences a separate function seemed a bit stupid to me.
I am open to feedback!
Thank you for this amazing software!
=> Bugfix: Check if API Key is used and valid

rcon/rcon.py
Hello!
I discovered the following bug:
Currently the filters in the "get_structued_logs" does not get applied, because the filter is applied after coping the line in the result. This PR patches that.
Thank you!
=> Bugfix: Apply filters before adding to result

rcon/rcon.py, rcon/utils.py
Hey, 
I found a typo in the API :(
The role "commmand" should be "command".
If you/we already do breaking changes, we should fix that too.
Thank you for looking into it!
=> Fix typo: Change "commmand" to "command

rcongui/src/components/PlayersHistory/index.js
* Use an empty array for the default value instead of `undefined` to allow the player history page to load correctly
=> Set blacklists to an empty list on initialization

rconweb/api/user_settings.py
Added required http methods to describe_chat_commands_config to prevent 500 Server Error
=> Hotfix: 500 Server Error on get_api_documentation

entrypoint.sh, rcon/cli.py
* Add a CLI command to convert windows store player IDs from the old format to the new format (md5 hash)
* Modify entrypoint.sh so player IDs are converted each start up
People should not install this release until they have shut down their game server, shut down CRCON, patched/re-enabled their game server and cleared their CRCON cache so that old style player IDs don't leak through (you could end up with multiple player ID records for the same windows store ID)
This can be run from the shell where you host CRCON with `docker compose exec backend_1 python -m rcon.cli convert_win_player_ids`
This took about 0.25 to 0.5 ms when testing it locally with ~300k player ID records.
=> Convert old styler player IDs on startup (for U15.2)

rcongui/src/components/SettingsView/hllSettings.js
The frontend failed to handle the `POST /api/set_votekick_thresholds` request because the endpoint now expects an `[int, int][]` array in version 10, whereas it accepted a `string` in version 9.
=> Fix votekick threshold due to API change

rcon/scoreboard.py
This fixes an issue when calculating stats (at least when recalculating, but it would be in the usual operation as well):
```
AttributeError("'TimeWindowStats' object has no attribute 'voted_no_regex'")
[2024-09-03 20:55:04,633][ERROR][][v10.3.0] rcon manage.py:<module>:55 | Unexpected error.
Traceback (most recent call last):
File "/code/./manage.py", line 45, in <module>
cli()
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx)) …
```
=> fix missing super call

rcon/automods/level_thresholds.py
Players having one of the `whitelist_flags` weren't immuned when violating `min_level` and `max_level`.
=> FIX---automod---level---whitelist-flags

rconweb/api/scoreboards.py
Include the map as a layer in `get_map_scoreboard`:
=> Return map layer info instead of just a plain map name

rcon/rcon.py
Hello,
`get_detailed_player_info` did not override the default `false` for `is_vip` and `null` for `profile` with the correct values. 
This PR fixes that and removes the workaround in `get_team_view` to not fetch the profiles twice. This also fixes the wrong value `is_vip` in `get_detailed_players`.
Thank you!
=> Bugfix: include is_vip and profile in get_detailed_player_info

alembic/versions/1e8fd0c19cb0_update_message_template_enum.py, rcon/types.py
* Adds `AUTO_SETTINGS` as a category for message templates so that different auto setting versions can be persisted in the database
=> Add auto settings to message templates

rconweb/api/auth.py
* Allows the `ws/logs` endpoint to accept a `sessionid` cookie for authentication
The header must be named `cookies` and the cookie itself named `sessionid`:
For example
`sessionid=3nu6qmb00pxh7qnqnpji3whxla6q8lxg`
=> Allow the ws/logs endpoint to authenticate with a sessionid cookie

rconweb/api/decorators.py
This is an elusive error that I've only seen when trying to use 4 or more game servers in the same CRCON install.
Doesn't make sense to me because it shouldn't matter and haven't looked into it further, but this will at least fix it for those people for now.
=> Don't crash on startup when using 4+ servers

rcon/hooks.py
These commands can be passed through to any type of rcon api, which might not just take strings as parameters´, but lists, dicts and so on as well.
=> Fix parameter handling in RCon Chat Commands

rcongui_public/src/components/game/statistics/player/index.tsx, rcongui_public/tailwind.config.js
A user can scroll the player detail without scrolling to the bottom of the page.
=> UI: Player detail made scrollable

rcongui_public/src/components/game/overview/index.tsx
Fixed public page stats arrow fix when it did not show up when match 0:5 or 5:0
=> UI: Bug fix - game score arrow display

rcongui/src/components/PlayerProfileDrawer/index.jsx, rcongui/src/utils/lib.js
- Better profile tab UI
- Name functions as a link to the player's profile
- ID can be copied to a clipboard by clicking a button
- New link to the player's platform profile - either Steam or Xbox
=> UI: Prettier player profile tab, platform link, cliboard id

rcongui/src/pages/views/live/logs-table.jsx
Issue: Player filter selection restarts every time the list of players involved in logs changes -> https://discord.com/channels/685692524442026020/706075642885832764/1320222405976920105
Fix: There was a for..in loop trough an Object that always resulted in setting all states to `false` as it should be for..of loop.
=> UI: Log table player filter selection restarts

rcongui/src/features/player-action/fields/ExpirationField.jsx, rcongui/src/features/player-action/forms/AddVipFormFields.jsx, rcongui/src/features/player-action/forms/BlacklistPlayerFields.jsx
Issue: 
- Time picker buttons don't work properly
- Blacklist perma bans no matter the provided time
Solution:
- Blacklist form field `name=expiration` -> `name=expires_at`
- When form value changed manually, it needs to force validation to re-render the component and update the TimePickerButtons date prop
=> UI: Fix VIP & Blacklist action form

rcongui/src/features/player-action/forms/AddVipFormFields.jsx
Issue: People are confused with the non-digit time picker buttons names
Solution: Make the names more descriptive
=> UI: VIP time picker button names

rcongui/src/utils/fetchUtils.js
Issue: Settings votekick thresholds crashes the app
Solution: added SET_VOTEKICK_THRESHOLDS command as it was missing
=> UI: Settings votekick thresholds crashes the app

rcongui/src/components/shared/RouteError.jsx, rcongui/src/config/siteConfig.js, rcongui/src/pages/settings/[configs]/detail.jsx, rcongui/src/pages/settings/index.jsx, rcongui/src/router.jsx, rcongui/src/utils/programminError.js
Issue: When programming or some other unexpected error, it displays only a blank page with some error text
Solution: Every route now falls back to new error element handling HTTP errors(no auth, no permission, ...) and all other general errors.
`REPORT` link directs to Discord Bug channel.
`BACK` link to refresh the page
=> UI: Better Error pages

rcongui/src/components/shared/SearchInput.jsx, rcongui/src/components/table/selection/LogActionHighlightMenu.jsx, rcongui/src/components/table/selection/LogActionSelectionMenu.jsx, rcongui/src/components/table/selection/LogPlayerSelectionMenu.jsx, rcongui/src/hooks/useSelectionMenu.js
Issue: The search input is not focused when the popover opens.
Solution: Adding `ref` to the input element and triggering `tabIndex=0` on popover's opened state.
=> UI: Log table selection popover input focus

rcongui/package-lock.json, rcongui/package.json, rcongui/src/components/shared/card/UsersCard.jsx, rcongui/src/features/player-action/forms/AddFlagFormFields.jsx, rcongui/src/features/player-action/forms/RemoveFlagFormFields.jsx, rcongui/src/pages/dashboard.jsx, rcongui/src/pages/views/live/players-columns.jsx
**This PR is dependent on #809. Merge only after #809 is merged into the master.**
- All occurrences of flags/emojis are now using `emoji-mart` library
- Removed `emoji-picker-react` library as it is not used any longer
Dashboard:
- Created `group.label` attribute to correctly render emojis in tab names
Live View:
- Player's table now displays up to 5 flags
=> UI: Flag emojis are not being displayed correctly

rcon/player_history.py
Hello,
this fixes #811 . The current implementation includes player where the blacklist record is already expired.
=> Fix: Show only player that are currently blacklisted, fixes #811

rcon/maps.py
* Change the base `Layer` and `Map` models to do case insensitive comparisons (it should be impossible to have identical but different case maps on the game server)
* Change the hard coded `Layer` and `Map` lookups to be case insensitive
I did build and test this locally, should be fine and should fix weird problems when the game server returns different cases than we expect.
```
In [2]: l1 = parse_layer("hill400_offensive_US")
In [3]: l2 = parse_layer("hill400_offensive_us")
In [4]: l1==l2
Out[4]: True
```
=> Do case insensitive map/layer lookups

rcongui_public/src/pages/games/horizontal-games-list.tsx
Bug: When selecting a game sometimes the window would scroll vertically. 
The issue was that it would scroll the Game Card to the top and ignored the sticky tool bar, but only if the site was scrollable (table was big enough).
https://discord.com/channels/685692524442026020/698857000804548629/1324752912055931021
=> FE: Stats: fixed: vertical scrolling while selecting different games

rconweb/api/audit_log.py, rconweb/api/auth.py, rconweb/api/auto_settings.py, rconweb/api/decorators.py, rconweb/api/history.py, rconweb/api/multi_servers.py, rconweb/api/services.py, rconweb/api/urls.py, rconweb/api/user_settings.py, rconweb/api/views.py, rconweb/api/vips.py
* Creates our own `permission_required` decorator which just passes through to Django's method so that we can track which permissions are required by endpoint
* Include the permission(s) required in `get_api_documentation` to make it easier to determine which access a user requires to consume the API (whether through a tool or the UI)
Output looks like:
```json
{
"endpoint": "add_admin",
"arguments": {
"player_id": {
"default": null,
"annotation": null
},
"role": {
"default": null,
"annotation": null
},
"description": {
"default": null,
"annotation": null
}
},
"return_type": "<class 'bool'>",
"doc_string": null,
"auto_settings_capable": true,
"permissions_required": [
"api.can_add_admin_roles"
],
"allowed_http_methods": [
"POST"
]
},
```
=> Include required permissions by endpoint in `get_api_documentation`

rcongui_public/src/components/game/statistics/game-table.tsx, rcongui_public/src/components/game/statistics/weapon-type-bar.tsx, rcongui_public/src/components/header/nav-links.tsx, rcongui_public/src/pages/games/horizontal-games-list.tsx, rcongui_public/src/pages/games/layout.tsx, rcongui_public/src/pages/games/list.tsx
1. valid games: offensive can be longer than 90 minutes (rare but can be the case)
2. Selecting older games would break the sticky date as the games array would change -> added key for rerender
3. added various missing keys in lists
4. removed the flexwrap from above the table as it is no longer necessary due to new player selection.
=> Small PR: some fixes

rcongui_public/src/components/game/statistics/download-button.tsx, rcongui_public/src/components/game/statistics/game-table.tsx
Public info is refetched every 15 seconds. 
This would rerender the whole table -> moved download hook in its own component
=> FE: Stats: fixed: table rerender

rcongui_public/src/components/language-selector/index.tsx, rcongui_public/src/i18n/config.ts, rcongui_public/src/i18n/locale-provider.tsx
Many people prefer english ingame, but are used to 24h DD MM YYYY format. 
Adds custom language 'en24h'
in i18n it acts exactly like 'en'
in dayjs it combines the 'en' translations for weekdays, months etc with the 'it' date format.
=> Feature: custom language en24h

rcon/user_config/log_line_webhooks.py, rcon/user_config/webhooks.py, tests/test_discord_handler.py
The UI is using JSON forms to generate elements based off the Pydantic schema the user config models generate.
It was causing issues with the admin ping settings because it did not think that `user_mentions` and `role_mentions` were required items because we default those to empty lists on the backend.
This removes the defaults, but still allows the model to be instantiated without passing them (important for resetting or generating new blank configs) by creating an empty list if they aren't provided.
The UI would also pass empty `""` strings for user/role mentions if not provided, which would fail validation so we simply filter those out.
=> Trick JSON forms into rendering the admin ping settings correctly

README.md
The Discord invite url I had expired.
I took the new one from [hllrcon.app](https://hllrcon.app/).
=> Readme   expired discord invite link

rcongui/src/pages/views/live/index.jsx, rcongui/src/queries/teams-live-query.jsx, rcongui/src/utils/lib.js
When any player have `player.profile=null` it does not show players in the table nor the game state.
Solution: Update `normalizePlayerProfile` to handle `null` cases.
=> UI: No players and gamestate is visible

rcongui/src/pages/records/players/index.jsx
Issue: `ignore_accent` always true on search
=> UI: Player records search ignores special chars

rcon/weapons.py
This PR adds `OQF 75MM [Churchill Mk.VII]` and `COAXIAL BESA 7.92mm [Churchill Mk.VII]` to the `BRITISH_WEAPONS` const in `weapons.py`.
Fixes #903
=> Fix: Add Churchill Mk.VII to British Weapon Definitions

rcon/logs/recorder.py, tests/test_log_recorder.py
When log lines are appearing in different runs off the log recorder, but have the same timestamp, they would be omitted, as the "last" log line already has this timestamp.
Some details of the analysis, how I came to the tests of that PR:
There is a greyhound night game here: https://greyrcon.de:82/games/2648
The player `🅶 I|I marsmyk` has 41 kills according to the stats page. In-game and reported by HLU, he has 43 kills, hence supposedly 2 kills are "missing".
In HLU, the player has the following kills recorded (excuse the german in the copy, it's just the line number):
```
Zeile 1176: 19:41:44 - Thu, Feb 13	KILL                	🅶 I|I marsmyk (Allies/76561198130579400) -> [82AD] Jakkas (Axis/76561198082971855) with M97 TRENCH GUN
Zeile 1534: 19:46:30 - Thu, Feb 13	KILL                	🅶 …
```
=> Fix not saving log lines

rcon/arguments.py, rcon/message_variables.py, rcon/types.py, tests/test_hooks.py
This can be used in every place where message variables are supported. With this commit, these variables are now also available in rcon chat commands. Most of them are potentially pretty useless, however, the new next_map_id might be helpful for cases where one wants to easily skip the current map to the next one in rotation. Either on a public server or on an event server (where only one map is in the rotation).
A command config should look like this:
```
{
"words": [
"!test2"
],
"description": "Testing layout",
"commands": {
"set_map": {
"map_name": "{next_map_id}"
}
},
"enabled": true,
"conditions": {}
}
```
=> Include next_map_id in RCon chat commands to skip current map

rcongui/src/components/layout/NavbarBreadcrumbs.js
- Refactored NavbarBreadcrumbs to use dynamic path-based breadcrumb generation
- Added BreadcrumbPopover component for nested navigation
- Implemented intelligent menu item path resolution
- Improved breadcrumb styling and interactivity
- Support for home link and nested menu navigation
=> UI: Enhance NavbarBreadcrumbs with Dynamic Navigation and Popover Menu

rcon/scoreboard.py, rcon/user_config/scoreboard.py, rcon/webhook_service.py
* Checks for the presence of the scoreboard volume on startup and log/exit if it isn't present. 
* This makes defining the volume in the `compose.yaml` file mandatory now.
* Handles HTTP 404 errors (message edits) more gracefully and will purge the message queue of remaining messages on failure
* Properly accept steam quick connect URLs for the scoreboard
* Include descriptions in the scoreboard fields
* Remove `show_map_rotation` field which was unused (superseded by a different field anyway)
I tested locally and made sure that the volume is accessible on the host file system and that data is still persisted even when the container is torn down/created again.
=> Test for presence of scoreboard volume on startup

rcongui/src/App.js, rcongui/src/components/form/core/ControlledDesktopDateTimePicker.jsx, rcongui/src/components/shared/card/LogsCard.jsx, rcongui/src/pages/records/game-logs/columns.jsx, rcongui/src/pages/records/game-logs/index.jsx, rcongui/src/pages/records/players/index.jsx
- Add timezone plugin to dayjs in App.js and game-logs page
- Modify date-time pickers to use 24-hour format (ampm=false)
- Update game logs column to convert event time to local timezone
- Remove explicit UTC timezone setting in players records page
=> UI: Game Logs timezone, 24-hour format date pickers

rcongui/src/components/shared/CopyableText.jsx, rcongui/src/pages/records/audit-logs/columns.jsx, rcongui/src/pages/records/audit-logs/index.jsx
=> UI: Audit logs - added player & id columns, sticky log detail

.github/workflows/docker-images.yml
A better implementation of: https://github.com/MarechJ/hll_rcon_tool/pull/975 thanks to @FlorianSW's suggestion.
Instead of splitting this into two separate github actions; instead we split the frontend/backend image building into two separate jobs so they will run in parallel with each other.
There is no reason we need these to build sequentially; this does mean that one build could fail and the other could succeed but that was the case before anyway I think.
In any event; a failed build can be easily restarted through GitHub even without access to the Docker Hub repository.
Builds should now only be as slow as the slowest of the two build processes; so we should have images roughly 2x as fast as before.
=> Use two concurrent jobs for parallel frontend/backend image building

rcon/hooks.py
FIX -- reset_watch_killrate_cooldown() needs arguments to call the @on_match_start constructor
Without arguments :
```
Traceback (most recent call last):
File "/code/rcon/logs/loop.py", line 348, in process_hooks
hook(self.rcon, log)
TypeError: reset_watch_killrate_cooldown() takes 0 positional arguments but 2 were given
```
With arguements :
```
[2025-02-28 16:26:24,585][INFO][LvL1][v11.4.5] rcon.logs.loop loop.py:process_hooks:344 | Triggered rcon.hooks.reset_watch_killrate_cooldown on [6.03 sec (1740759977)] MATCH START MORTAIN Warfare
```
=> FIX -- reset_watch_killrate_cooldown() needs arguments to call the @on_match_start constructor

rcongui/src/components/game/Points.jsx, rcongui/src/components/game/Team.jsx, rcongui/src/components/table/styles.jsx, rcongui/src/pages/stats/games/[gameId]/game-columns.jsx, rcongui/src/pages/stats/live-sessions/columns.jsx, rcongui/src/pages/views/live/players-columns.jsx, rcongui/src/pages/views/team/team-section.jsx
Here's a suggestion for more readability within the UI.
I added some tooltips to the Header of the Tables in some of the pages for easier orientation when new to the UI. Some of them may seem self explanatory but I added them for consistency anyway.
=> UI: add tooltips to tables and images

rcongui/src/components/Blacklist/BlacklistRecordGrid.js, rcongui/src/pages/records/blacklists/index.jsx
Hi, 
this is a suggestion for the blacklist footer to better tell the two infos apart. 
I added spacing to the blacklist footer grid and fixed some ide and console warnings on the way. 
old: <img width="274" alt="Screenshot 2025-03-25 at 21 33 14" src="https://github.com/user-attachments/assets/bba88763-3966-489e-9bad-b00b6b6f2d58" />
new:  <img width="298" alt="Screenshot 2025-03-25 at 21 33 02" src="https://github.com/user-attachments/assets/322a1941-c2bd-48e7-aeb0-e7e404b8cc5a" />
=> UI: add space to blacklist record footer

rcongui_public/src/pages/games/list.tsx
Some games are not showing up as those were considered invalid games due to map changes or games that keep hanging while the server is idle.
This change reflects U17.1 changes.
=> Adjust game validation lenghts U17.1

rcongui/src/components/layout/sidebar/About.jsx
This should fix it. Either they changed the property name or there was some merge issue at some point or entirely my f up.
=> UI: Fix version in About modal

rcongui/src/components/layout/SideMenu.js, rcongui/src/components/layout/SideMenuMobile.js, rcongui/src/components/layout/sidebar/About.jsx, rcongui/src/components/layout/sidebar/ConnectionStatus.jsx, rcongui/src/components/layout/sidebar/SystemUsage.jsx, rcongui/src/components/layout/sidebar/utils.js, rcongui/src/features/title-manager/TitleManager.jsx, rcongui/src/stores/global-state.js, rcongui/src/utils/fetchUtils.js, rconweb/api/views.py, requirements.txt
Added cpu, ram and disk usage information.
A minor change in styling the bottom section about connection and version details.
I believe this is useful information to have and save some logging into the environment directly.
🆕 API endpoint `/api/get_system_usage`
> example
```
{
"cpu_usage": {
"cores": 4,
"percent": 10.4,
"process_count": 4
},
"ram_usage": {
"total": 15.244922637939453,
"used": 7.427345275878906,
"percent": 51.5
},
"disk_usage": {
"total": 149.91522216796875,
"used": 26.94037628173828,
"percent": 18.7
}
}
```
=> Display system usage information
